[server]
port = 8080
data_dir = "./data"

[tokens]
youtube = "AIzaSyDOQcLZAhFsLdE5F_yVTjUvBNjgJQivnRA"

[feeds]
  [feeds.ID1]
  url = "https://www.youtube.com/playlist?list=PLklI4fp4DoMiWIZSMwv1OJ4yByBI8pv1-" # URL address of a channel, group, user, or playlist. 
  page_size = 50 # The number of episodes to query each update (keep in mind, that this might drain API token)
  update_period = "12h" # How often query for updates, examples: "60m", "4h", "2h45m"
  quality = "high" # or "low"
  format = "video" # or "audio"
  # cover_art = "{IMAGE_URL}" # Optional URL address of an image file
