version: '2.2'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./data:/app/data/
      - ./config.toml:/app/config.toml
